### ISSUE TITLE
Git string comparison issue

### ISSUE THREAD

**Issue by ytcs** [ucbpylegroup/CutBucket#6]
In cuts.py:
`    357         if not self.repo.git.status().split('\n')[1] == f"Your branch is up to date with 
 origin/{self.branch}'.":`

On some machine the git client returns Your branch is **up-to-date** with origin (note the hyphens), which breaks the check.

**Comment by cwfink** [comment]
hmm. I think the real problem is that this is probably just not a great way of doing this check at all, but i'm unsure off the top of my head of a better way.  I can change this quickly to check for either case for the time being.
